@startuml GET Dentist All Appointments (GET)

header Appointments API Sequence Diagram
footer Page %page% of %lastpage%
title "GET Dentist All Appointments (GET)"

participant "Client" as client
participant "<<javaScript>>\n:server" as server
participant "<<router>>\n:dentists" as routerDentists
participant "<<router>>\n:appointments" as routerAppointments
participant "<<controllers>>\n:appointments" as controllersAppointments
participant "<<model>>\n:Appointment" as modelAppointment
database "<<MongoDB>>\n:appointments" as AppointmentsDatabase

client->server ++:req.get('/dentists/:dentistId/appointments')
server->routerDentists ++:app.use('/dentists',dentists)
routerDentists->routerAppointments ++:app.use('/:dentistId/appointments',appointments)
routerAppointments -> controllersAppointments ++:getAllAppointments()
controllersAppointments->modelAppointment ++:find({ dentist: req.params.dentistId })
modelAppointment ->AppointmentsDatabase ++: AppointmentSchema
AppointmentsDatabase --> modelAppointment --: appointments
controllersAppointments <-- modelAppointment --:appointments
controllersAppointments->client --:response

@enduml