@startuml Update Single Dentist (PUT)

header Dentists API Sequence Diagram
footer Page %page% of %lastpage%
title "Update Single Dentist (PUT)"

participant "Client" as client
participant "<<javaScript>>\n:server" as server
participant "<<router>>\n:dentists" as routerDentists
participant "<<middleware>>\n:auth" as middlewareAuth
participant "<<controllers>>\n:dentists" as controllersDentists
participant "<<model>>\n:Dentist" as modelDentist
database "<<MongoDB>>\n:dentists" as DentistsDatabase

client->server ++:req.put('/dentists/:id')
server->routerDentists ++:app.use('/dentists',dentists)
routerDentists -> middlewareAuth ++:protect()
alt token
    middlewareAuth -> routerDentists --:next()
else !token || token == "null"
    middlewareAuth -> client --:res.status(401).json({error: 'Not authorized to access this route'})
end

routerDentists -> middlewareAuth ++:authorize('admin')
alt req.user.role === 'admin'
    middlewareAuth -> routerDentists --:next()
else req.user.role !== 'admin'
    middlewareAuth -> client --:res.status(403).json({error: 'User role not authorized to access this route'})
end

routerDentists -> controllersDentists ++:updateDentist(req.params.id, req.body)
controllersDentists->modelDentist ++:findByIdAndUpdate(req.params.id, req.body)
modelDentist ->DentistsDatabase ++: DentistSchema
DentistsDatabase --> modelDentist --: updatedDentist
controllersDentists <-- modelDentist --:updatedDentist
controllersDentists->client --:response

@enduml